name: Test on PR
on:
  pull_request:
    branches: [main]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Run Forge Coverage
        run: |
          forge coverage > ./coverage-report.md
        id: coverage

      - name: Report Coverage in PR
        uses: thollander/actions-comment-pull-request@v2.3.1
        with:
          filePath: ./coverage-report.md
          comment_tag: coverage-report